jobs:
   # Set all global variables
   #
   - name: Init
     exec: >
        global.packPath = getOPackPath("nAttrMon") || ".";
        global.config = (isDef(args.withDirectory)) ? args.withDirectory : global.packPath + "/config";
        log("Scanning " + global.packPath);

   # Cleaning function
   # 
   - name: Clean functions
     exec: >
        var clean = (aFile) => { log("Removing " + aFile); io.rm(aFile); };
        var cleanDir = (aFile) => { log("Removing " + aFile); io.rm(aFile); };

   # Cleaning all snapshots files
   #
   - name: Clean snapshots
     from: Clean functions
     deps:
        - Init
     exec: >
        clean(global.config + "/nattrmon.attrs.snapshot");
        clean(global.config + "/nattrmon.cvals.snapshot");
        clean(global.config + "/nattrmon.lvals.snapshot");
        clean(global.config + "/nattrmon.warns.snapshot");

   # Cleaning H2 database files
   #
   - name: Clean H2 database
     from: Clean functions
     deps:
        - Init
     exec: >
        clean(global.config + "/nattrmon_db");
        // TO BE COMPLETED

   # Cleaning pid file
   # 
   - name: Clean pid file
     from: Clean functions
     deps:
        - Init
     exec: >
        clean(global.packPath + "/nattrmon.pid");

   # Cleaning logs
   - name: Clean logs
     from: Clean functions
     deps:
        - Init
     exec: >
        cleanDir(global.config + "/log");

   # Everything done
   # 
   - name: Done
     deps: 
        - Init
        - Clean snapshots
        #- Clean H2 database
        - Clean pid file
     exec: >-
        log("Done");
todo:
   - Init
   - Clean snapshots
   #- Clean H2 database
   - Clean pid file
   - Clean logs
   - Done