kind: output
constructor: nOutput_RemoteChannel
title: nOutput_RemoteChannel
description: Configuration metadata for nOutput_RemoteChannel.
examples:
  - config/outputs.disabled/yaml/03.pushChannels.yaml
arguments:
  - name: attrTemplate
    type: any
    description: Configuration option read by nOutput_RemoteChannel.
    example: Category/Name
  - name: exclude
    type: any
    description: Configuration option read by nOutput_RemoteChannel.
    example: {}
  - name: idKey
    type: any
    description: Configuration option read by nOutput_RemoteChannel.
    example: {}
  - name: include
    type: any
    description: Configuration option read by nOutput_RemoteChannel.
    example: {}
  - name: url
    type: any
    description: Configuration option read by nOutput_RemoteChannel.
    example: {}
  - name: valueKey
    type: any
    description: Configuration option read by nOutput_RemoteChannel.
    example: {}
