input:
# -------------------------------
- name       : Test Java GC local
  #cron         : "*/15 * * * * *"
  #waitForFinish: true
  #onlyOnEvent  : false
  execFrom   : nInput_JavaGC
  execArgs   :
    type        : local
    attrTemplate: "Java/{{_name}}"
    #nameSummary   : GC Summary
    #nameCollectors: GC Collectors
    #nameThreads   : Threads
    #nameSpaces    : GC Spaces
    #nameMem       : Memory
    #includeSummary   : true
    #includeCollectors: true
    #includeThreads   : true
    #includeSpaces    : true
    #includeMem       : true

# -----------------------------
- name       : Test Java GC ssh
  #cron         : "*/15 * * * * *"
  #waitForFinish: true
  #onlyOnEvent  : false
  execFrom   : nInput_JavaGC
  execArgs   :
    type        : ssh
    chKeys      : sshServers
    attrTemplate: "Remote/Java {{_name}}"
    #nameSummary   : GC Summary
    #nameCollectors: GC Collectors
    #nameThreads   : Threads
    #nameSpaces    : GC Spaces
    #nameMem       : Memory
    #includeSummary   : true
    #includeCollectors: true
    #includeThreads   : true
    #includeSpaces    : true
    #includeMem       : true

# ------------------------------
- name       : Test Java GC kube
  #cron         : "*/15 * * * * *"
  #waitForFinish: true
  #onlyOnEvent  : false
  execFrom   : nInput_JavaGC
  execArgs   :
    type        : kube
    kube        :
      namespace: my-namespace-1, my-namespace-2
      selector :
        where:
        - cond: starts
          args:
          - metadata.name
          - my-pod
        - cond: equals
          args:
          - status.phase
          - Running
    attrTemplate: "Kube/Java {{_name}}"
    #nameSummary   : GC Summary
    #nameCollectors: GC Collectors
    #nameThreads   : Threads
    #nameSpaces    : GC Spaces
    #nameMem       : Memory
    #includeSummary   : true
    #includeCollectors: true
    #includeThreads   : true
    #includeSpaces    : true
    #includeMem       : true