input:
# -------------------------------
- name       : Test Java GC local
  #cron         : "*/15 * * * *"
  #waitForFinish: true
  #onlyOnEvent  : true
  execFrom   : nInput_JavaGC
  execArgs   :
    type        : local

# -----------------------------
- name       : Test Java GC ssh
  #cron         : "*/15 * * * *"
  #waitForFinish: true
  #onlyOnEvent  : true
  execFrom   : nInput_JavaGC
  execArgs   :
    type        : ssh
    chKeys      : sshServers
    attrTemplate: Servers/Java GC

# ------------------------------
- name       : Test Java GC kube
  #cron         : "*/15 * * * *"
  #waitForFinish: true
  #onlyOnEvent  : true
  execFrom   : nInput_JavaGC
  execArgs   :
    type        : kube
    kube        :
      namespace: my-namespace-1, my-namespace-2
      selector :
        where:
        - cond: starts
          args:
          - metadata.name
          - my-pod
        - cond: equals
          args:
          - status.phase
          - Running
    attrTemplate: Kube/Java GC