input:
# --------------------
- name    : Input init
  execFrom: nInput_Init
  execArgs:
    CH:
    - name   : jmxs
      entries:
      - key  : test1
        value:
          url: service:jmx:rmi:///jndi/rmi://127.0.0.1:9999/jmxrmi

# -------------------
- name    : Input jmx
  #cron         : "*/15 * * * *"
  #waitForFinish: true
  #onlyOnEvent  : true
  execFrom: nInput_JMX
  execArgs:
    chKeys : jmxs
    objects:
    - object  : "java.lang:type=OperatingSystem"
    - object  : "java.lang:type=Runtime"
      path    : "{SpecName:SpecName,SpecVendor:SpecVendor,SpecVersion:SpecVersion,ManagementSpecVersion:ManagementSpecVersion,InputArguments:InputArguments,BootClassPathSupported:BootClassPathSupported,VmName:VmName,VmVendor:VmVendor,VmVersion:VmVersion,Uptime:Uptime,StartTime:StartTime,Name:Name,ClassPath:ClassPath}"
      #selector:
    - object  : "java.lang:type=Memory"
    - object  : "java.lang:type=Compilation"
    - object  : "java.lang:type=Threading"
      path    : "{CurrentThreadAllocatedBytes:CurrentThreadAllocatedBytes,ThreadCount:ThreadCount,TotalStartedThreadCount:TotalStartedThreadCount,CurrentThreadCpuTime:CurrentThreadCpuTime,CurrentThreadUserTime:CurrentThreadUserTime,PeakThreadCount:PeakThreadCount,DaemonThreadCount:DaemonThreadCount}"
      #selector:
    - object: "java.lang:type=MemoryManager,name=Metaspace Manager"
    - object: "java.lang:type=MemoryPool,name=Metaspace"