name: Update pack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  UpdatePack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    - name: Generate oPack
      uses: OpenAF/ojob-action@v3
      with:
        script: oPack("genpack . --exclude .github")
        dist  : 't8'
        
    - name: Update version badge
      uses: OpenAF/ojob-action@v3
      with:
        def : |
          todo:
          - Update badge with version

          ojob:
            opacks:
            - Badgen

          include:
          - badgen.yaml

          jobs:
          # -------------------------------
          - name: Update badge with version
            from: Get version
            to  :
            - name: Badgen generate file
              args: 
                labelColor: grey2
                color     : blue
                icon      : "nattrmon_grey.svg"
                label     : "repo opack version"
                file      : ".github/version.svg"

          # -----------------
          - name: Get version
            exec: args.status = getOPackRemoteDB()["nAttrMon"].version
        dist: 't8'
        
    - name: Checkin
      env:
        GH_TOKEN: ${{ github.token }}
      uses: OpenAF/ojob-action@v3
      with:
        ojob: 'ojob.io/git/hub/checkIn'
        args: 'message="Update\ package" title="Update\ package"'
        dist: 't8'
